src/DatabasesSecondLabotaroryAuth/Controllers/DefectsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DAL.Models;
using DatabasesSecondLabotaroryAuth.Data;
using DAL.DAO;
using DAL.DAO.Interfaces;
using Microsoft.AspNetCore.Hosting;
using System.IO;
using Microsoft.AspNetCore.Http;

namespace DatabasesSecondLabotaroryAuth.Controllers
{
    public class DefectsController : Controller
    {
        private readonly IDefectRepository defectsRepository;
        private readonly IHostingEnvironment hostingEnvironment;
        private readonly IPhotoRepository photosRepository;

        public DefectsController(IDefectRepository defectsRepository, 
            IHostingEnvironment hostingEnvironment,
            IPhotoRepository photosRepository)
        {
            this.defectsRepository = defectsRepository;
            this.hostingEnvironment = hostingEnvironment;
            this.photosRepository = photosRepository;
        }

        // GET: Defects
        public IActionResult Index()
        {
            return View(defectsRepository.GetAll());
        }

        // GET: Defects/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var defect = defectsRepository.Get(id.Value);
            if (defect == null)
            {
                return NotFound();
            }

            return View(defect);
        }

        // GET: Defects/Create
        public IActionResult Create()
        {
            return View(new Defect());
        }

        // POST: Defects/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Defect defect)
        {
            if (defectsRepository.Exists(defect))
            {
                ModelState.AddModelError(string.Empty, "Defect already exists");
            }
            if (ModelState.IsValid)
            {
                foreach(Photo photo in defect.Photos)
                {
                    photo.Path = SaveFile(photo.PhotoFile);
                }
                defectsRepository.Create(defect);
                return RedirectToAction("Index");
            }
            return View(defect);
        }

        // GET: Defects/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var defect = defectsRepository.Get(id.Value);
            if (defect == null)
            {
                return NotFound();
            }
            return View(defect);
        }

        // POST: Defects/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, Defect defect)
        {
            if (id != defect.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    foreach(Photo photo in defect.Photos)
                    {
                        if (photo.Id == 0)
                        {
                            photo.Path = SaveFile(photo.PhotoFile);
                            photo.DefectId = id;
                            photo.NewlyInserted = true;
                            photo.Id = photosRepository.Create(photo);
                        }
                    }
                    defectsRepository.Update(id, defect);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DefectExists(defect.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(defect);
        }

        // GET: Defects/Delete/5
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var defect = defectsRepository.Get(id.Value);
            if (defect == null)
            {
                return NotFound();
            }

            return View(defect);
        }

        // POST: Defects/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            var defect = defectsRepository.Get(id);
            defectsRepository.Delete(id);
            return RedirectToAction("Index");
        }

        private string SaveFile(IFormFile formFile)
        {
            var uploads = "wwwroot/uploads/";
            if (formFile != null && formFile.Length > 0)
            {
                var filePath = Path.Combine(uploads, formFile.FileName);
                using (FileStream fileStream = new FileStream(filePath, FileMode.Create))
                {
                    formFile.CopyTo(fileStream);
                    return filePath;
                }
            }
            return string.Empty;
        }

        private bool DefectExists(int id)
        {
            return defectsRepository.Get(id) != null;
        }
    }
}

src/DatabasesSecondLabotaroryAuth/Controllers/ReportsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using DAL.DAO.Interfaces;
using DAL.Models;

namespace DatabasesSecondLabotaroryAuth.Controllers
{
    public class ReportsController : Controller
    {

        private readonly IReportsRepository reportsRepository;

        public ReportsController(IReportsRepository reportsRepository)
        {
            this.reportsRepository = reportsRepository;
        }

        public IActionResult CompanyTypes()
        {
            List<CompanyTypeReportRow> results = reportsRepository.GetCompanyTypesReport();
            return View(results);
        }

        public IActionResult MeasureUnits(int? minAmount, int? maxAmount)
        {
            if (minAmount.HasValue && maxAmount.HasValue)
            {
                List<MeasureUnitReportRow> results = reportsRepository.GetMeasureUnitsReport(minAmount.Value, maxAmount.Value);
                return View(results);
            }
            return View();
        }

        public IActionResult Vehicles(string fragment)
        {
            if (!string.IsNullOrEmpty(fragment))
            {
                return View(reportsRepository.GetVehicleReport(fragment));
            }
            return View();
        }

    }
}

src/DatabasesSecondLabotaroryAuth/Controllers/VehiclesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DAL.Models;
using DatabasesSecondLabotaroryAuth.Data;
using DAL.DAO.Interfaces;
using DatabasesSecondLabotaroryAuth.Models.ComplexCreateModels;

namespace DatabasesSecondLabotaroryAuth.Controllers
{
    public class VehiclesController : Controller
    {

        private readonly IVehicleRepository vehicleRepository;
        private readonly ICompanyRepository companyRepository;
        private readonly IVehicleTypeRepository vehicleTypeRepository;

        public VehiclesController(IVehicleRepository vehicleRepository,
            ICompanyRepository companyRepository, IVehicleTypeRepository vehicleTypeRepository)
        {
            this.vehicleRepository = vehicleRepository;
            this.companyRepository = companyRepository;
            this.vehicleTypeRepository = vehicleTypeRepository;
        }

        public IActionResult Index()
        {
            return View(vehicleRepository.GetAll());
        }

        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vehicle = vehicleRepository.Get(id.Value);
            if (vehicle == null)
            {
                return NotFound();
            }

            return View(vehicle);
        }

        // GET: Vehicles/Create
        public IActionResult Create()
        {
            ViewData["CompanyId"] = new SelectList(companyRepository.GetAll(), "Id", "Title");
            ViewData["VehicleTypeId"] = new SelectList(vehicleTypeRepository.GetAll(), "Id", "Title");
            return View(new VehicleCreateModel()
            {
                Vehicles = new List<Vehicle>()
                {
                    new Vehicle()
                },
                VehicleTypes = new List<VehicleType>()
                {
                    new VehicleType()
                }
            });
        }

        // POST: Vehicles/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(VehicleCreateModel model)
        {
            foreach (VehicleType vehicleType in model.VehicleTypes)
            {
                if (vehicleTypeRepository.Exists(vehicleType))
                {
                    ModelState.AddModelError(string.Empty, "VehicleType already exists");
                }
                if (ModelState.IsValid)
                {
                    vehicleType.Id = vehicleTypeRepository.Create(vehicleType);
                }
            }
            foreach (Vehicle vehicle in model.Vehicles)
            {
                if (vehicleRepository.Exists(vehicle))
                {
                    ModelState.AddModelError(string.Empty, "Vehicle already exists");
                }
                if (ModelState.IsValid)
                {
                    VehicleType previouslyStoredType = vehicleTypeRepository.GetByTitle(vehicle.VehicleType.Title);
                    if (previouslyStoredType != null)
                    {
                        vehicle.VehicleTypeId = previouslyStoredType.Id;
                        vehicleRepository.Create(vehicle);
                    }
                }
            }
            if (ModelState.IsValid)
            {
                return RedirectToAction("Index");
            }
            ViewData["CompanyId"] = new SelectList(companyRepository.GetAll(), "Id", "Title");
            ViewData["VehicleTypeId"] = new SelectList(companyRepository.GetAll(), "Id", "Title");
            return View(model);
        }

        // GET: Vehicles/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vehicle = vehicleRepository.Get(id.Value);
            if (vehicle == null)
            {
                return NotFound();
            }
            ViewData["CompanyId"] = new SelectList(companyRepository.GetAll(), "Id", "Title", vehicle.CompanyId);
            ViewData["VehicleTypeId"] = new SelectList(vehicleTypeRepository.GetAll(), "Id", "Title", vehicle.VehicleTypeId);
            return View(vehicle);
        }

        // POST: Vehicles/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("Id,LicensePlates,CompanyId,VehicleTypeId")] Vehicle vehicle)
        {
            if (id != vehicle.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    vehicleRepository.Update(id, vehicle);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VehicleExists(vehicle.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            ViewData["CompanyId"] = new SelectList(companyRepository.GetAll(), "Id", "Title", vehicle.CompanyId);
            ViewData["VehicleTypeId"] = new SelectList(vehicleTypeRepository.GetAll(), "Id", "Title", vehicle.VehicleTypeId);
            return View(vehicle);
        }

        // GET: Vehicles/Delete/5
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vehicle = vehicleRepository.Get(id.Value);
            if (vehicle == null)
            {
                return NotFound();
            }

            return View(vehicle);
        }

        // POST: Vehicles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            var vehicle = vehicleRepository.Get(id);
            vehicleRepository.Delete(id);
            return RedirectToAction("Index");
        }

        private bool VehicleExists(int id)
        {
            return vehicleRepository.Get(id) != null;
        }
    }
}

src/DatabasesSecondLabotaroryAuth/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DatabasesSecondLabotaroryAuth</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/lib/jquery-ui-1.12.1/jquery-ui.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/lib/jquery-ui-1.12.1/jquery-ui.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    @Html.ApplicationInsightsJavaScript(TelemetryConfiguration)
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">DatabasesSecond</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <!--<li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>-->
                    <li><a asp-area="" asp-controller="MeasureUnits" asp-action="Index">MeasureUnits</a></li>
                    <li><a asp-area="" asp-controller="Materials" asp-action="Index">Materials</a></li>
                    <li><a asp-area="" asp-controller="CompanyTypes" asp-action="Index">CompanyTypes</a></li>
                    <li><a asp-area="" asp-controller="Companies" asp-action="Index">Companies</a></li>
                    <li><a asp-area="" asp-controller="Vehicles" asp-action="Index">Vehicles</a></li>
                    <li><a asp-area="" asp-controller="Defects" asp-action="Index">Defects</a></li>
                    <li><a asp-area="" asp-controller="Reports" asp-action="CompanyTypes">CompanyReports</a></li>
                    <li><a asp-area="" asp-controller="Reports" asp-action="MeasureUnits">UnitReports</a></li>
                    <li><a asp-area="" asp-controller="Reports" asp-action="Vehicles">VehicleReports</a></li>
                </ul>
                @*@await Html.PartialAsync("_LoginPartial"*@
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - DatabasesSecondLabotaroryAuth</p>
        </footer>
    </div>

    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>